project:
  type: upfthesis
  output-dir: "_thesis"

book:
  date-format: "YYYY"
  chapters:
    - "index.qmd"
    - "chapters/01-introduction.qmd"
    - "chapters/02-chapter-2.qmd"
    - "chapters/03-chapter-3.qmd"
    - "chapters/04-discussion.qmd"
    - "chapters/05-bibliography.qmd"
    - "chapters/06-glossary.qmd"
  output-file: thesis

thesis:
  title: "Bilingual Insights into the Initial Lexicon"
  subtitle: "The Role of Cognates in Word Acquisition"
  author: "Gonzalo Garcia-Castro"
  date: 2023
  department: "Department of Experimental and Health Sciences"
  supervisor: "Dr. Núria Sebastián-Gallés"
  dedication: |
    A mamá, a papá, a Íñigo.
  acknowledgements: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor quis quam non feugiat. Fusce a eleifend sapien. Fusce vel ipsum vitae purus molestie venenatis in in nunc. Fusce blandit placerat ullamcorper. Aliquam erat volutpat. Integer sed ante porttitor, egestas neque at, molestie neque. In id ante ultricies leo molestie tristique id a tortor. Vivamus ullamcorper, lectus vitae tristique accumsan, nunc nulla cursus urna, in ultricies eros odio nec arcu. Etiam non convallis nulla. Nunc imperdiet nibh at scelerisque interdum. Vivamus mattis placerat justo, nec maximus ligula rutrum et. Sed ut rhoncus dui, ut dignissim justo. Donec vitae sapien tempus, dictum libero sit amet, tincidunt leo. Maecenas auctor libero pellentesque finibus porta.
    Curabitur pretium augue odio, a porttitor purus pellentesque vitae. Maecenas lobortis justo ut eleifend blandit. Morbi nulla dolor, imperdiet eget lacus non, accumsan bibendum turpis. Aenean nec viverra est. Duis laoreet nulla ut diam mattis, vitae pellentesque nibh fringilla. Morbi pellentesque, ante a faucibus auctor, diam augue vehicula dui, auctor interdum sem augue at risus. In hac habitasse platea dictumst. Nam sit amet consectetur lacus, eget gravida orci. Fusce suscipit varius dapibus. Aenean enim mi, vestibulum vitae mi maximus, molestie efficitur odio. Duis aliquam blandit sagittis. Nulla ut volutpat erat.
    Curabitur id ligula dolor. Ut convallis augue mi, sed rutrum urna facilisis eu. Nullam mollis tortor eget massa eleifend pellentesque. Etiam placerat faucibus placerat. Sed et auctor ligula. Pellentesque at dictum ante. Etiam et tempus augue. Sed id elit nibh. Aliquam erat volutpat. Sed vel sem elit.
  abstract-english: "Bilingual infants acquire words at a similar rate than monolinguals ones, despite facing a more complex linguistic environment. The mechanisms underlying this achievement are unclear. We investigated the possible role of cognateness---form-similarity across translation equivalents (TEs)---as a facilitator of bilingual lexical growth. We first modelled the acquisition trajectories of TEs, and found a facilitation effect of cognateness, only in the language of lower exposure. We provided a mechanistic account for this effect, rooted in the language non-selective hypothesis of lexical access. We then tested the plausibility of a central assumption in this account: that bilingual infants activate TEs in both languages in parallel, even during monolingual situations. We used a primed word recognition task in which participants were tested in exclusively one of their languages, while we covertly manipulated the cognateness of the prime words. Overall, we provide insights into the role of language non-selectivity in the initial bilingual lexicon."
  abstract-catalan: "Els infants bilingües adquireixen paraules a un ritme comparable als monolingües, malgrat una exposició a un entorn lingüístic més complex. En aquesta tesi, investiguem el paper de la cognasticitat (similitud en forma entre traduccions equivalents o TEs) com a facilitador de l'expansió del lèxic. El modelatge de les trajectòries d'adquisició de les TEs, ha mostrat un efecte de facilitació de la cognasticitat a la llengua amb menor exposició. El resultats s’expliquen a través de la hipòtesi de l'accés lèxic no selectiu. Mitjançant una tasca de reconeixement de paraules a la que es va manipular la cognasticitat de las paraules experimentals de manera encoberta, s'ha posat a prova el pressupòsit de que els infants bilingües activen les TEs en ambdues llengües simultàniament en situacions monolingües. Aquesta tesi aporta coneixements significatius sobre el paper de la no-selectivitat lingüística en el lèxic inicial.
"
  preface: "Some things are more easily talked about than done. Talking about *talking*---an activity sometimes referred to as *Linguistics*---is however painfully difficult. The action of *talking* feels extremely easy for most humans. In fact, learning how to talk seems trivial for most infants. Language is the most complex communicative system known, yet very few people are surprised by the fact that infants pick it up so early in life, and so effortlessly. Developmentalists, however, are intrigued by early language acquisition and its implications on human cognition and evolution.  How infants acquire the most complex communicative system know by humans in such a short time span is a question that has kept many folks out of unemployment, including myself for the last five years. This thesis explores a small area of language acquisition research: how infants learn a specific type of linguistic unit called *words*, and whether bilingualism---the simultaneous acquisition of two language---impacts this process. Although some of the premises and claims expressed in the present work may apply to infants acquiring language though modalities other than the auditory, the scope of the present work is the developmental trajectories of hearing, typically developing infants. For this reason, most examples and arguments concern the auditory modality, and refer to events that are specifically relevant to hearing infants, like *sound*, *hearing*, *auditory*. We invite the reader to consider the case of deaf infants as a natural extension of the point made, whenever possible. For instance, note that we adopt a broad definition of *phonology* in which a phonological system is present, with the only difference to oral languages that the forms of the linguistic units is motor-visual."
format:
  upfthesis-pdf:
    page-crop: frame # cam, crop, frame
    page-info: noinfo # info, noinfo
    lot: true # show list of tables? (not required)
    lof: true # show list of figures? (not required)
    linestretch: 1.5 # can be 1 or 1.5
    include-in-header:
      text: |
        \usepackage{tipa}
        \usepackage{booktabs}
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
  upfthesis-docx: default

fig-dpi: 500
fig-align: center
lang: en

echo: false
warning: false
message: false
freeze: auto

csl: "_assets/apa7.csl"
bibliography:
  - "_assets/refs-introduction.bib"
  - "_assets/refs-chapter-2.bib"
  - "_assets/refs-chapter-3.bib"

  