---
title: Introduction
number-sections: true
---


Some things are more easily talked about than done. Language is the opposite. Talking about *talking*---an activity sometimes referred to as *Linguistics*---is painfully difficult, but the action of *talking* feels extremely easy for most humans. In fact, learning how to talk seems trivial for most infants. How infants acquire the most complex communicative system know by humans in such a short time span is a question that has kept many folks busy, including myself for the last five years. This thesis explores a small area of language acquisition research. In particular, how infants learn a specific type of linguistic unit called *words*, and whether bilingualism (the simulatenous acquisition of two languages) impacts this process.

## Early language acquisition

### Why is language important

Language does not exist in the absence of its users.

Language is tuned to what our bodies can do.

### An incomplete overview of language acquisition

Small local changes from which bigger phenomena emerge (Rethinking).

Developmental mechanisms.

Developmental trajectories. Non-linearity in the output is not necessarily generated by non-linear changes in the input. Multiple small linear changes in the system can lead to big non-linear changes in the output [@elman1W994rethinking].

### Words

## The mental lexicon

* Jackendoff (pp. 39, p. 3): finite list of structural elements that are available to be combined through a finite set of combinatorial principles, or *grammar*.

A note on represenations. Jackendoff (pp. 20, p. 3).

A note on lexicalism:

* Lexical items: words, morphemes? Lexical formation rules and lexical relations [Jackendoff pp 40]
* Lexical items may embedd grammatical information.
* In a distributed account of lexical representations, gramatical knowledge about words emerges from the activation patterns elicited by the presentation of similar tokens in similar positions (and with similar dependencies) across contexts [@elman1990; @elman1994rethinking].

Assumptions: 

* Rooted in the computation theory of mind.
* Distributed: phonemes, word-forms, and concepts are represented across multiple nodes that contain feature information across multiple levels.
* Nodes need not map directly into anatomical unit. We do not make assumptions on whether the neuron populations in which representations are implemented are themselves local or distributed.
* We also do not make assumptions about to what extent the connectionist metaphor of the lexicon is real or not. We find it useful to generate explanations and make predictions.
* Nodes are connnected, and their connections are characterised by weights, which indicate the strength of the connection. The strenght of the connection between two representations is subject to learning.
* Activation spreads across nodes, so that the activation of a given node is modulated by the activation of connected nodes.
* Connections across levels are excitatory, connections within levels (lateral connections) are inhibitory.
* Baseline activation: lexical frequency

### Word recognition

### Word production

### Word acquisition: Building a lexicon

Word learning vs. word acquisition.

Word learning mechanisms.

Measureing word acquisition.



## The bilingual lexicon


### Definig bilingualism

### Bilingual word comprehension

* Activation vs. inhibition within and across languages.

### Bilingual word production

* Activation vs. inhibition within and across languages.

### Bilingual word acquisition

The intersection between offline and online.

Mutual exclusivity.



## The present thesis

### General aim

#### Word acquisition

#### Word recognition

### Defining cognateness through phonological similarity

### Measuring phonological similarity

### A methodological note on statistical inference

Bayesian statistics.

### Predictions and relevance
