---
title: Discussion
---

The aim of the present thesis was to investigate the initial bilingual lexicon. We explored the role of cross-language lexical similarity on word acquisition, and its possible impact on the dynamics of lexical access. In this concluding chapter, we summarise the results from Chapters 2 and 3. We then elaborate on the implications of our findings on theoretical, and comment on some of the methodological limitations encountered. We also discuss possible steps to take in future research. We conclude highlighting the main contributions of the thesis.

## Summary of results

In Chapter 2, we investigated how cognateness affects word acquisition in 10 to 32 month-old bilinguals learning Catalan and Spanish. We used Item Response Theory (IRT) to model the acquisition trajectories of a large sample of Catalan and Spanish words, and found a facilitation effect of cognateness on the probability of comprehension and production. This facilitation was mediated by an *ad hoc* index of word exposure, which adjusted the lexical frequency of the words for the dual linguistic input of bilinguals. Low-exposure words benefited more strongly from their cognate status, whereas words with average or high exposure were unaffected by their cognate status. We interpreted these results as evidence in favour of language non-selectivity playing a central role the initial lexicon. In particular, we suggested that exposure instances to words in one language contributed, to some extent as exposure instances to their translation equivalents.

Our account for the results found in Chapter 2 built on the assumption that bilingual infants co-activate the translation equivalents in both languages, even during monolingual situations, in which they hear words in exclusively one of the languages. Previous experimental work on language non-selectivity in the initial lexicon relied on paradigms in which participants are presented with words from the two languages during the same testing session, introducing them into a bilingual context [@von2012language; @floccia2020translation; @jardak2019labels; @singh2014one]. To our knowledge, no previous study had tested whether language non-selectivity takes place in fully monolingual paradigms. We addressed this gap in the literature in Chapter 3. We tested language non-selectivity in infants using an implicit naming paradigm, adapted from Mani and Plunkett [-@mani2010infant; -@mani2011phonological]. Participants were presented with an exclusively monolingual task. By manipulating the cognate status of prime words, and its impact on subsequent recognition of phonologically related words, we aimed to test whether participants co-activated translation equivalents in both languages in monolingual situations. Methodological caveats in the adaptation of the task prevented us from draw conclusions from this experiment.

## Towards a model of bilingual vocabulary growth

Differences in the developmental trajectories of word acquisition across bilingual populations has gained some attention in last decade. It had been previously established that, on average, bilingual infants learn words at a similar rate as monolinguals, despite facing a more challenging word-learning task [@pearson1993lexical; @pearson1994patterns; @poulin2013lexical; @core2013total; @byers2023sometimes; @bosch2014first]. An influential monograph by @floccia2018introduction provided evidence for a possible mechanism behind bilingual word acquisition: bilingual toddlers learning two lexically similar languages (e.g., English-Dutch) show larger productive vocabularies than those learning two lexical, less similar languages (e.g., English-Mandarin). This suggested that some populations of bilinguals may exploit the similarities between their languages---particularly, the phonological similarity between translation equivalents---to acquire words faster [see also @gampe2021does]. The authors pointed at the language non-selective hypothesis of lexical access as the mechanism behind this cross-language facilitation effect. How the dynamics of lexical access in the initial lexicon might relate to word acquisition was still to be addressed.

In Chapter 2, we provided a theoretical account for the findings in @floccia2018introduction. We extended the notion of *accumulator*---borrowed from accumulator models of language acquisition---to the bilingual case. We hypothesised that, as infants accumulate learning instances with words in one language, they also accumulate learning instances with their translation equivalents, in an extent proportional to the phonological similarity between each pair of word-forms. This account built on the assumption that infants co-activate translation equivalents in both languages during language exposure, and that the activation of the lexical representation of each word may count as a learning instance with such word by the infant. In line with this account, participants acquired cognates earlier than non-cognates [in line with previous findings by @mitchell2022cognates], even after controlling for lexical frequency, relative language exposure, and word length. This facilitation effect was stronger in words to which participants were exposed less often.

Our results converge with two main predictions from our proposal. First, the earlier age of acquisition for cognates than for non-cognates is in line with a faster accumulation of learning instances for cognates. This might be the result of cognate words receiving stronger co-activation from their translation equivalents than non-cognates, given their higher phonological similarity, leading to cognates receiving such additional activation more often than non-cognates. The asymmetry in the size cognateness facilitation effect between high-exposure and low-exposure words provides further support for this explanation. Words with lower lexical frequency or belonging to participants' less dominant language (in which they receive less input) should benefit more strongly from the additional co-activation provided by their (more frequently activated) translation, than higher exposure words, which might receive such additional co-activation less frequently. This mechanism may explain to some degree the facilitative role of lexical similar reported by @floccia2018introduction, and the asymmetry found in the size of such effect between the English vocabulary and the additional-language vocabulary in their participants. Since English was the dominant language for most participants in their sample, it is possible that the increment in vocabulary size drive by cognates was stronger in the additional language, leading to a larger facilitation effect of lexical similarity. In summary, these results have important consequences for current models of bilingual lexical acquisition.

The model of lexical acquisition presented in Chapter 2 built on the assumption that bilingual infants activate translation equivalents in parallel during language exposure---even in monolingual situations---in line with the language-non selective hypothesis of lexical access. As previously mentioned, evidence indicating that bilingual infants co-activate translation equivalents in both languages during monolingual situations was scarce. The aim of Chapter 3 was to test bilingual infants in a primed word recognition task, in which stimuli were only presented in their dominant language. This task was an adaptation of the implicit naming paradigm, by Mani and Plunkett [-@mani2010infant; -@mani2011phonological] in which primes are presented in the form of pictures shown in silence to participants. In the original studies, by Mani and Plunkett showed that 18 and 21 month-old English monolinguals lexicalised such prime pictures, generating phonologically detailed internal labels. This was revealed by the fact that infants spoken word recognition was influenced by the prior presentation of an picture whose label shared phonological overlap with the target word. Later studies provided evidence of such implicit naming at earlier ages [@duta2012erp; @styles2015infant]. In our implementation of the task, we manipulated the degree of phonological overlap between prime and target labels, and the cognate status of the prime labels. We predicted that, if bilinguals activate prime words in both languages---in line with the language non-selective account of lexical access---priming effects would be stronger when the prime labels are cognates, both overlapping phonologically with the subsequently recognised word. Our adaptation of this task failed to produce the anticipated effects, and even to reproduced the results from the original studies in monolinguals. We interpreted this as the result of methodological complications driven by the adjustments we conducted on the original procedure.

## Methodological contributions

A considerable part of the present dissertation has built on a database of vocabulary data collected from 2020 onwards. To gather this database, we designed and implemented an *ad hoc* questionnaire the Barcelona Vocabulary Questionnaire (BVQ) [@garcia2023bvq]. This questionnaire was filled in by a large sample of families of monolinguals and bilinguals aged 10 to 32 months, learning Catalan and Spanish. Collected data included comprehension and production estimates for individual words in Catalan and Spanish. Queries to the database can be performed through its associated R package `bvq` ([https://gongcastro.github.io/bvq](https://gongcastro.github.io/bvq)), which provides a sizable amount of acquisition reports, and may be used to address further research questions about bilingual lexical development. In addition, this questionnaire was developed open source software, and all the materials and code used in process are available at the GitHub repository ([https://github.com/gongcastro/bvq](https://github.com/gongcastro/bvq)).

Another contribution of the present dissertation is the modelling approach adopted throughout Chapters 2 and 3. We highlight two features of interest. First, we adopted a Bayesian approach to parameter estimation and statistical inference. This approach provides great advantages, compared to the more widespread frequentist approach. Among them, we highlight the possibility to incorporate previous knowledge about the distribution of parameters of interest in a model, providing a more stable and efficient computation of the posterior coefficients. This proved to be a valuable asset in the implementation of complex multilevel structures for the random effects of the models, which we describe below. Some participants contributed partial datasets, in which for particular combinations of levels of the predictors of interested, few observations were gathered, if any. In these cases, a frequentist approach would most likely have provided unstable inferences, if not computational complications (e.g., convergence issues during the estimation of parameters). Following a Bayesian approach, we specified a weakly informative prior for the parameters in our models, so that incoming observations would  gradually update the shape of the distribution of the parameters until data collection concluded. At no point the parameters of the models provided infeasible estimates, as the distribution of their parameters was constrained by theoretically grounded prior distributions.

In Chapter 2, caregivers of many ---but not all of---participants provided answers about comprehension or production for the same words. Conversely, the same participant provided such responses to multiple---but not all of---words. To analyse this type of datasets, previous studies aggregated scores across items or participants, in order to avoid violations of the assumption of independence between the residuals of related observations (e.g., belonging to the same participant) [@floccia2018introduction; @bosch2014first]. As a consequence, information at participant-level or item-level was not available in subsequent analyses. On the contrary, in this dissertation we incorporated the complex data collection design into the structure of our model in the form of Item Response Theory (IRT), in which participants and words were included as crossed random effects in the random effects structure of the model. Data analysis in Chapter 3 also benefited from this approach, given its complex data collection design, in which some participants were tested more than once. In this case, we included participants and testing sessions as nested random effects. In summary, the present dissertation benefited from a Bayesian approach to statistical inference that may be of interest for future research in language acquisition.

## Limitations and future research

One of the main pitfalls encountered in this dissertation were the experimental caveats in Chapter 3. Our adaptation of the original implicit naming task by Mani and Plunkett [-@mani2010infant; -@mani2011phonological] failed to reproduce the expected results. We introduced some adjustments to the structure of the trial, in order to maximise the probability of detecting cross-language priming effects. Such effects are short-lived and more difficult to detect than within language priming effects. For this reason, we removed the pre-naming phase of the trial, in which target and distractor pictures are presented prior to the auditory target label. This made the presentation of the prime picture and the target auditory label closer in time. We expected the immediacy of the presentation of both stimuli to increase of the size of the priming effect. Instead, this adjustment appeared to disrupt the lexical retrieval of the priming label, in such way that priming effects were not observed in any of the experimental conditions. This prevented us from drawing any conclusions about the presence of such effects in the initial lexicon from this experiment. Future research should address whether a longer inter-stimulus interval between the presentation of the prime and the target would lead to the observation of priming effects.

The present dissertation contributes several open questions. One of them is whether the cognate facilitation effect reported in Chapter 2 is present in other populations of bilinguals, namely those learning more lexically dissimilar languages. As mentioned in the Discussion section of Chapter 2, Catalan and Spanish share many cognates. This may bias infants into expecting word-forms to hold a form-similar translation equivalent, and being more prompt to co-activate form-similar words in both languages than infants who encounter fewer cognates in their linguistic input. For instance, infants learning English and Mandarin, two languages that share very few cognates, may not be able to exploit cross-language similarity to boost the acquisition of words in both languages during language exposure. The approach followed by @floccia2018introduction [see also @siow2023double; @floccia2020translation] of collecting data from infants learning a diverse pool of language pairs would be convenient for addressing this issue.

The evidence provided in Chapter 2 in favour of an earlier age of acquisition of cognates does not address the particular mechanisms infants may use to accumulate information about word forms and their association to their corresponding referents. We used the term *learning instance* [@mollica2017data] to refer to exposures to a word in which infants *may* use to consolidate its lexical representation. Determining the specific condition under which a learning instance is effective (i.e., may lead to word learning) falls out of the scope of the present dissertation. We simply assume that some learning instances may be effective, and that the number of effective learning instance is a function of the total number of learning infants a child encounters on a daily basis. An experimental approach to word learning, in which the impact of cognateness is investigated, would provide valuable insights into the mechanisms behind the role of cross-linguistic similarity on word acquisition.

For instance, a recent study by @tsui2023patterns provides a potentially suitable paradigm to investigate the impact of cognateness on online word learning. The authors designed a word learning task in which they tested bilingual infants aged 3-to-5 years of age, learning French and English (in Montreal, Canada), and Spanish and English (in New Jersey, United States). In the learning phase, participants were trained to associate novel labels to novel objects. At test, participants were presented with pairs of objects encountered in the learning phase, and a label that corresponded to one of them. Participants were instructed to select the corresponding object in a touchscreen. Participants completed two blocks of training and test phases. In the training phase of one block, participants were presented with sentences labelling the novel objects in both languages in an interleaved fashion. For instance, in one trial they would be presented with a novel object, which would be labelled in English (e.g., *gasser* in English). In the next trial, they would be presented with the same object, which this time would be labelled in French (e.g., *donquete* in French, or *sasco* in Spanish). This condition simulated a *language mixing* environment (i.e., children are exposed to both languages in the same situations, encountering words from both languages interleaved in speech), to which a sizeable proportion of bilinguals are exposed [@byers2013parental]. In the training phase of the other block, participants were presented with consecutive trials labelling the object in the same language, and then with consecutive trials labelling the object in the other language. This condition simulated a *one-language-at-a-time* environment. Overall, participants succeeded at learning the words in both conditions. This suggests that infants benefit equally from being exposed to labelling events in alternating languages in an interleaved fashion (a bilingual environment) and in an synchronous fashion (monolingual situations).

@tsui2023patterns used phonologically distinct novel labels across languages. By extending this paradigm it could be possible to investigate whether participants learning of the label-referent associations is facilitated by the degree of phonological between the translation equivalents. If participants co-activate newly learned translation equivalents in both languages, word learning should be facilitation more strongly by the repetition of phonologically similar translation equivalents (i.e., cognates) than from the repetition of phonologically dissimilar translation equivalents (i.e. non-cognates). Another variable of interest for such experimental paradigm could be the lexical similarity between the two languages being acquired. The two populations of bilinguals in @tsui2023patterns, ones exposed to French and English, and the others to Spanish-English, were learning two languages belonging to two different typological families. At the lexical level both pairs of languages are relatively distant, compared to languages belonging to the same family, like Catalan and Spanish. By comparing how bilinguals process cognates in world learning contexts, depending on the overall lexical similarity of their languages (e.g., high in the case of Catalan and Spanish, low in the case of Euskera and Spanish), it could be possible to investigate how the linguistic input shapes the strategies followed by bilinguals during early lexical development. In summary, future steps may involve experimental paradigms to investigate the mechanisms involved in the cognate facilitation of word acquisition with more details, and with a finer control of the conditions in which participants are exposed to the word-forms.


## Conclusions

The present dissertation provides insights into the developing bilingual lexicon. We provided evidence in favour of a mechanistic account of word acquisition, in which bilinguals exploit the language non-selectivity of their lexicon to facilitate the acquisition of cognate words. These findings have important consequences for the current understanding of bilingual vocabulary growth, and in particular, the mechanisms underlying the parallel trajectories of lexical acquisition of monolinguals and bilinguals.

\clearpage