## Abstract

Bilingual infants acquire words at a similar rate than monolinguals, despite facing a more complex linguistic environment. The mechanisms underlying this achievement are unclear. We investigated the possible role of cognateness---form-similarity across translation equivalents (TEs)---as a facilitator of bilingual lexical growth. We first modelled the acquisition trajectories of TEs, and found a facilitation effect of cognateness, only in the language of lower exposure. We provided a mechanistic account for this effect, rooted in the language non-selective hypothesis of lexical access. We then tested the plausibility of a central assumption in this account: that bilingual infants activate TEs in both languages in parallel, even during monolingual situations. We used a primed word recognition task in which participants were tested in exclusively one of their languages, while we covertly manipulated the cognateness of the prime words. Overall, we provide insights into the role of language non-selectivity in the initial bilingual lexicon.

## Resum

Els infants bilingües adquireixen paraules a un ritme comparable als monolingües, malgrat exposar-se a un entorn lingüístic més complex. En aquesta tesi, investiguem el paper de la cognasticitat (similitud en forma entre traduccions equivalents o TE) com a facilitador de l'expansió del lèxic. Hem modelat les trajectòries d'adquisició de les TE, revelant un efecte de facilitació de la cognasticitat en el llengua amb menor exposició. Expliquem aquests resultats mitjançant la hipòtesi no selectiva de l'accés lèxic, i vam posar a prova la suposició que els infants bilingües activin les TE en ambdues llengües simultàniament en situacions monolingües. Vam fer servir una tasca de reconeixement de paraules en la qual els participants van ser provats exclusivament en una de les seves llengües, mentre que les paraules primes es manipulaven de manera encoberta. Aquesta tesi aporta coneixements significatius sobre el paper de la no-selectivitat lingüística en el lèxic primerenc.

## Resumen

Los niños bilingües adquieren palabras a un ritmo comparable a los monolingües, a pesar de exponerse en un entorno lingüístico más complejo. En esta tesis, investigamos el papel de la cognasticidad (similitud en forma entre traducciones equivalentes o TE) como facilitador de la expansión del léxico. Hemos modelado las trayectorias de adquisición de TE, revelando un efecto facilitador de la cognasticidad en la lengua de menor exposición. Explicamos estos resultados mediante la hipótesis no selectiva del acceso léxico, y pusimos a prueba la suposición que los niños bilingües activen las TÉ en ambas lenguas simultáneamente en situaciones monolingües. Usamos una tarea de reconocimiento de palabras en la cual los participantes fueron probados exclusivamente en una de sus lenguas, mientras que las palabras primas se manipulaban de manera encubierta. Esta tesis aporta conocimientos significativos sobre el papel de la no-selectividad lingüística en el léxico temprano.