---
bibliography: ../refs-introduction.bib
---

Talking about *talking*---an activity sometimes referred to as *Linguistics*---is painfully difficult. Language is the most complex communicative system known, yet few people are surprised by the fact that infants pick it up so early in life, and so effortlessly. Some of those few intrigued people are developmentalists, whose scientific enterprise has kept a lucky bunch of them out of unemployment. For the last five years, I have been one of them. In this dissertation, I present some of the contributions that have resulted from these years.

We addressed the case of bilingual infants, who are being raised in two languages. In particular, we investigated how such dual language exposure impacts the emergence of a mental lexicon, where phonological and conceptual representations find each other. We focused on the case of bilingual language acquisition as an extension of the monolingual case, which may provide insights about how language acquisition is shaped by different experiences with language.

It is known to the developmentalist that the trajectories of language acquisition of different infants may diverge substantially. Some of the sources of this individual variability have been identified and are under investigation. Cross-linguistic differences is one of them. Infants learning two different languages may follow slightly different paths towards language acquisition. This is also the case for bilingual infants. An influential monograph by @floccia2018introduction showed that the specific pair of languages that a bilingual child is learning affects their trajectories of vocabulary growth. In particular, they found that 24-month-old bilinguals were able to produce more words when their languages were lexically more similar (e.g., English-Dutch), compared to when both languages were lexically less similar (e.g., English-Mandarin). The motivation of this dissertation is to investigate the mechanisms underlying such facilitation effect.

The first goal of this dissertation was to provide a mechanistic explanation to the effect found by @floccia2018introduction. We focused on the role of *cognates* (i.e., phonologically similar translation equivalents). We tested the hypothesis that cognate words are acquired earlier by children than non-cognate words. This would explain why participants in @floccia2018introduction, who were learning lexically similar languages (i.e., shared many cognates) had larger vocabulary sizes than those learning two languages with less lexical similarity (i.e., shared fewer cognates). We first put forward the foundations of a model that involved the interaction between lexical frequency, quantitative language exposure, and cognateness, to generate a cognateness facilitation on word acquisition. We then designed a vocabulary questionnaire, the Barcelona Vocabulary Questionnaire (BVQ), which we used to collect vocabulary data from monolingual and bilingual participants living in the Metropolitan Area of Barcelona. These participants were learning Catalan and Spanish, two Romance languages with high lexical similarity. We modelled comprehension and production estimates of a large sample of children to test the predictions of our model of word acquisition.

A second goal of this dissertation was to test the plausibility of a central assumption behind the model proposed in Chapter 2: that bilingual infants co-activate both languages during language exposure, even in monolingual situations. Previous studies had provided evidence in this direction, but had relied on paradigms in which participants were introduced into a bilingual environment while completing the task. We addressed this in Chapter 3. In collaboration with Prof. Kim Plunkett and Dr. Serene Siow, from the University of Oxford, we designed an experimental task that would test the language non-selectivity of the developing bilingual lexicon in a purely monolingual context. For more than three years, we worked together, collecting data from a large cohort of monolinguals and bilinguals in both Oxford and Barcelona. Despite our efforts, methological complications kept us from being able to address the hypotheses of interest.

This was not the only setback we encountered during our research. The COVID-19 was an important setback for the project. First, it severely limited our access to participants for the experimental task in both locations. First, universities were completely shut down during the lockdown imposed by the governments in both Spain and United Kingdom, meaning that access to laboratories was not possible, even for researchers. During these times, only online data collection could be conducted. Second, it became challenging to find participants, even after the lockdown was lifted. This was especially the case in Oxford, where bilingual participants were already hard to find. Some families did offer to us their time and interest, and took part in the testing sessions once the universities opened and the appropriate protocols were established. We are very grateful to them.

The timings and the aims of the project had to be adjusted to the circumstances. For instance, due to the tight schedule that we were left with after the lockdown, we decided to resume data collection in both laboratories in parallel. Initially, we planned to first conclude data collection in Oxford, were the original studies from which we adapted the experimental task were run. This would allow us to first replicate the original findings in the same population of monolinguals, making sure that the procedure would be an appropriate tool to test our hypotheses before moving to monolingual and bilingual infants in Barcelona. This was not possible. Unfortunately, we were unable to replicate the original findings, keeping us from drawing conclusions about our predictions in the experimental section of the present dissertation.

Despite the obstacles encountered during the collection and analysis of the experimental data in Chapter 3, I believe the present dissertation provides valuable insights into the early stages of the bilingual lexicon. In the discussion section, we elaborate on the these contributions, putting our theoretical proposal from Chapter 2, its assumptions, and its implications, in the center. We present this proposal as the Accumulator Model of Bilingual Lexical Acquisition (AMBLA). We illustrate the rationale behind this model by simulating word acquisition trajectories that mirror the results obtained in Chapter 2. We conclude this dissertation with a discussion on future experimental and modelling work to follow the formalisation of AMBLA.

Throughout the preparation of this dissertation, we paid special attention into maximising transparency. The code used to run the experiments, and to collect and analyse the anonymised data, are accessible in the version-controlled GitHub repositories of their respective studies. I am aware that full computational reproducibility is not possible without a substantial increase in the programming knowledge required from the reproducing researcher. I have made an effort to provide extensive documentation on the required steps for reproducing the analyses in this thesis. I have also made available a Docker image for each of the studies included in this dissertation. Opening these images should allow anyone to run the scripts in their local machine with all pre-installed dependencies in a relatively convenient way. Materials and results (e.g. heavy files, like model fits) are also available in the corresponding Open Science Framework repositories. The source code and materials used to write and render the present dissertation are available in a stand-alone GitHub repository ([https://github.com/gongcastro/thesis](https://github.com/gongcastro/thesis)).

